Task-27-Send-alert-after-create-disaster
jkuznik/disaster-alerts pull request #31
Opened 2024-10-24 08:09 UTC by Slawek84PL

2024-10-24 15:53 UTC, jkuznik approved these changes

2024-10-26 16:51 UTC, RobertoJavaDev requested changes

2024-10-26 16:51 UTC, RobertoJavaDev commented on src/main/java/pl/ateam/disasteralerts/disasteralert/DisasterServiceImpl.java
> +    public void addDisasterFromWeb(DisasterAddWebDTO disasterAddWebDTO) {
Pytanie czy nie możemy tego ujednolicić i zrobić jedną metodę addDisaster?
Zamiast addDisaster i addDisasterFromWeb?

2024-10-28 08:58 UTC, RobertoJavaDev approved these changes

2024-10-28 09:03 UTC, merged