Task 4 - Thymeleaf
jkuznik/disaster-alerts pull request #6
Opened 2024-10-12 18:38 UTC by YamiHeike

Dodałam:
* Dependencję pod Thymeleaf
* Plik index.html oraz IndexViewController
W pliku index.html dołączyłam Bootstrap oraz przykładowy prosty template ze stroną do logowania i kontrolkami potrzebnymi do implementacji Usera.

2024-10-12 19:28 UTC, jkuznik commented
![Zrzut ekranu 2024-10-12 o 21 23 50](https://github.com/user-attachments/assets/e2c51e2d-9fa7-4647-9f36-0721975dc8ca)

Wszystko działa

2024-10-12 19:29 UTC, jkuznik approved these changes

2024-10-13 05:28 UTC, RobertoJavaDev requested changes
Ładnie to wygląda

2024-10-13 05:28 UTC, RobertoJavaDev commented on src/main/resources/templates/index.html
> +                    </div>
Dodaj jeszcze proszę przycisk do zalogowania się - "Sign in"

2024-10-13 05:32 UTC, RobertoJavaDev commented on src/main/resources/templates/index.html
> +                    <button class="w-100 btn btn-lg btn-primary" type="submit">Sign up</button>
Dodaj jeszcze proszę przycisk do zalogowania się - "Sign in"

2024-10-13 07:36 UTC, Slawek84PL approved these changes
Fajne ;)

2024-10-13 09:03 UTC, merged