Add Swagger configuration
jkuznik/disaster-alerts pull request #8
Opened 2024-10-13 05:57 UTC by jkuznik

Dodałem konfigurację swagger z nastawieniem na obsługę samego swagger z wykorzystaniem pliku yaml. Szablon dodawania zawartości samego yamla -> https://editor.swagger.io/

Daje to możliwość opisania poszczególnych endpointów bez zaciemniania kodu w klasie kontrolera adnotacjami swaggera

Przykładowy kod dla metody PATCH w kontrolerze oraz rezultat w swagger gdzie dla wygody PathVariable oraz RequestBody są predefiniowane przed wykonaniem testowego zapytania
![image](https://github.com/user-attachments/assets/55c9f5a5-fd04-40d8-8143-e9f619735253)
![image](https://github.com/user-attachments/assets/1fd02f60-a3fd-4e48-9862-77572a76e846)

2024-10-14 17:49 UTC, RobertoJavaDev approved these changes

2024-10-14 17:50 UTC, RobertoJavaDev requested changes
Trzeba rozwiązać konflikty.

2024-10-14 21:16 UTC, jkuznik commented
This branch has no conflicts with the base branch - aktualny status PR,

 pipeline nie przechodzi z powodu braku changelogów z CREATE TABLE

2024-10-15 03:52 UTC, Slawek84PL approved these changes

2024-10-15 04:39 UTC, merged